### ISSUE TITLE
フッターのクレジットの年表記が、昨年のままになってしまっている

### ISSUE THREAD

**Issue by unstoppa61e** [shun0918/blog-nextjs#31]
## スクリーンショット
![スクリーンショット 2022-04-14 6 10 55](https://user-images.githubusercontent.com/46347198/163271284-1781e355-a79e-4b3c-b6a4-1c31968e213d.png)

**Comment by shun0918** [comment]
そういえば忘れていました💀
わざわざご指摘ありがとうございます！修正しました！

**Comment by unstoppa61e** [comment]
@shun0918 
突然の Issue 立てで驚かせてしまい、すみませんでした🙏
ご対応、ありがとうございました😄
